export const meta = {
  name: 'forge-plan',
  description: 'forge phase: typed-clause plan, mechanical checks, clause critic',
}
// GENERATED by forge/build.js from forge/src — edit there, then run `bun build.js`.
// Pure helpers shared by every forge phase. No imports, no I/O: build.js strips
// `export` and inlines this file into each workflow script.

// ---------- sha256 (scripts have no crypto API) ----------

const SHA_K = [
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]

function utf8Bytes(str) {
  const out = []
  for (const ch of str) {
    const c = ch.codePointAt(0)
    if (c < 0x80) out.push(c)
    else if (c < 0x800) out.push(0xc0 | (c >> 6), 0x80 | (c & 63))
    else if (c < 0x10000) out.push(0xe0 | (c >> 12), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63))
    else out.push(0xf0 | (c >> 18), 0x80 | ((c >> 12) & 63), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63))
  }
  return out
}

const rotr = (x, n) => (x >>> n) | (x << (32 - n))

const byteLength = str => utf8Bytes(str).length

function sha256(str) {
  const bytes = utf8Bytes(str)
  const bitLen = bytes.length * 8
  bytes.push(0x80)
  while (bytes.length % 64 !== 56) bytes.push(0)
  const hi = Math.floor(bitLen / 0x100000000)
  const lo = bitLen >>> 0
  bytes.push((hi >>> 24) & 255, (hi >>> 16) & 255, (hi >>> 8) & 255, hi & 255,
    (lo >>> 24) & 255, (lo >>> 16) & 255, (lo >>> 8) & 255, lo & 255)
  const H = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]
  const W = new Array(64)
  for (let i = 0; i < bytes.length; i += 64) {
    for (let t = 0; t < 16; t++) {
      W[t] = (bytes[i + 4 * t] << 24) | (bytes[i + 4 * t + 1] << 16) | (bytes[i + 4 * t + 2] << 8) | bytes[i + 4 * t + 3]
    }
    for (let t = 16; t < 64; t++) {
      const s0 = rotr(W[t - 15], 7) ^ rotr(W[t - 15], 18) ^ (W[t - 15] >>> 3)
      const s1 = rotr(W[t - 2], 17) ^ rotr(W[t - 2], 19) ^ (W[t - 2] >>> 10)
      W[t] = (W[t - 16] + s0 + W[t - 7] + s1) | 0
    }
    let [a, b, c, d, e, f, g, h] = H
    for (let t = 0; t < 64; t++) {
      const t1 = (h + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ (~e & g)) + SHA_K[t] + W[t]) | 0
      const t2 = ((rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) | 0
      h = g; g = f; f = e; e = (d + t1) | 0; d = c; c = b; b = a; a = (t1 + t2) | 0
    }
    H[0] = (H[0] + a) | 0; H[1] = (H[1] + b) | 0; H[2] = (H[2] + c) | 0; H[3] = (H[3] + d) | 0
    H[4] = (H[4] + e) | 0; H[5] = (H[5] + f) | 0; H[6] = (H[6] + g) | 0; H[7] = (H[7] + h) | 0
  }
  return H.map(x => (x >>> 0).toString(16).padStart(8, '0')).join('')
}

// ---------- JUnit ----------

function unescapeXml(s) {
  return s
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&')
}

const normFile = f => (f || '').replace(/^\.\//, '')

// Reads full JUnit XML or the grep stream the runner returns (open tags, closing
// tags and `<failure type="…"` fragments, one per line).
function parseJunit(xml) {
  const cases = []
  for (const m of String(xml).matchAll(/<testcase\b([^>]*?)(\/>|>([\s\S]*?)<\/testcase>)/g)) {
    const attrs = {}
    for (const a of m[1].matchAll(/([\w:-]+)="([^"]*)"/g)) attrs[a[1]] = unescapeXml(a[2])
    const body = m[3] || ''
    const failure = body.match(/<(?:failure|error)\b[^>]*?\btype="([^"]*)"/)
    const failed = /<(?:failure|error)\b/.test(body)
    cases.push({
      name: attrs.name,
      file: normFile(attrs.file),
      outcome: failed ? 'fail' : /<skipped\b/.test(body) ? 'skip' : 'pass',
      failureType: failed ? (failure ? unescapeXml(failure[1]) : '') : null,
    })
  }
  return cases
}

// A test missing from the report was never collected: an import or compile error
// removes the whole file from bun's XML.
function outcomes(tests, cases) {
  return tests.map(t => {
    const c = cases.find(k => k.name === t.name && k.file === normFile(t.file))
    return c ? c.outcome : 'not-collected'
  })
}

function junitCommand(testCmd, outFile) {
  if (/^bun test\b/.test(testCmd)) return `${testCmd} --reporter=junit --reporter-outfile=${q(outFile)}`
  return null
}

// ---------- triage ----------

const SIGNALS = ['persistence', 'auth', 'money', 'concurrency', 'untrusted-input', 'public-api', 'data-loss']
const TIERS = ['S', 'M', 'L']

function sizeOf(files, newModules = 0) {
  const n = new Set(files).size
  if (n > 8) return 'L'
  if (n > 2 || newModules > 0) return 'M'
  return 'S'
}

const raiseTier = (a, b) => (TIERS.indexOf(a) >= TIERS.indexOf(b) ? a : b)

function riskOf(signals, dismissedIds) {
  const live = signals.filter(s => !dismissedIds.includes(s.id))
  return { risk: live.length ? 'high' : 'low', signals: live }
}

function parseDismiss(list) {
  return (list || []).map(item => {
    const m = String(item).match(/^\s*([\w-]+)\s*:\s*(\S.*)$/)
    if (!m) throw new Error(`dismiss "${item}" needs a reason: "<signal id>: <reason>"`)
    return { id: m[1], reason: m[2].trim() }
  })
}

// SPEC §6 table — the only source for council, shadow, checkpoints and attackers.
function dosing(tier, risk) {
  const high = risk === 'high'
  const small = tier === 'S'
  return {
    council: !small && high,
    shadow: high,
    checkpointAfterPlan: !(small && !high),
    checkpointAfterSlice: !small && high,
    attackers: high ? ['opus', 'opus'] : [small ? 'sonnet' : 'opus'],
    mutation: high,
  }
}

// ---------- plan checks ----------

const KINDS = ['behavior', 'negative', 'preserve', 'migration', 'concurrency', 'property']
const REQUIRED = {
  auth: ['negative'],
  persistence: ['migration', 'negative'],
  concurrency: ['concurrency'],
  'untrusted-input': ['property', 'negative'],
  money: ['negative'],
  'data-loss': ['negative'],
  'public-api': ['preserve'],
}
const CLAUSE_FIELDS = ['id', 'kind', 'input', 'action', 'expected', 'source']

function checkPlan(plan, { signals = [], sources = [] } = {}) {
  const slices = (plan && plan.slices) || []
  if (!slices.length) return ['plan has no slices']
  const problems = []
  const seen = new Set()
  const used = new Set()
  const signalIds = [...new Set(signals.map(s => s.id))]
  for (const slice of slices) {
    if (!slice.files || !slice.files.length) problems.push(`${slice.id}: no files`)
    if (!slice.spec || !slice.spec.length) { problems.push(`${slice.id}: no clauses`); continue }
    for (const c of slice.spec) {
      for (const f of CLAUSE_FIELDS) if (typeof c[f] !== 'string' || !c[f].trim()) problems.push(`${c.id || slice.id}: empty ${f}`)
      if (c.kind && !KINDS.includes(c.kind)) problems.push(`${c.id}: unknown kind ${c.kind}`)
      if (seen.has(c.id)) problems.push(`duplicate clause id ${c.id}`)
      seen.add(c.id)
      used.add(c.source)
    }
    for (const id of signalIds) {
      const need = REQUIRED[id]
      if (need && !slice.spec.some(c => need.includes(c.kind))) {
        problems.push(`${slice.id}: signal ${id} needs a ${need.join(' or ')} clause`)
      }
    }
  }
  const rejected = new Set(((plan && plan.rejected) || []).map(r => r.id))
  for (const s of sources) if (!used.has(s) && !rejected.has(s)) problems.push(`${s} is neither a clause source nor rejected`)
  return problems
}

// ---------- git, shell, run layout ----------

const q = s => `'${String(s).replace(/'/g, `'\\''`)}'`

const unquotePath = p => (p.startsWith('"') && p.endsWith('"') ? JSON.parse(p) : p)

function parsePorcelain(text) {
  return String(text).split('\n').filter(l => l.length > 3).map(l => {
    const path = l.slice(3)
    const arrow = path.indexOf(' -> ')
    return unquotePath(arrow >= 0 ? path.slice(arrow + 4) : path)
  })
}

const PROTECTED = [
  /(^|\/)package\.json$/, /(^|\/)bunfig\.toml$/, /(^|\/)tsconfig[^/]*\.json$/,
  /(^|\/)(bun\.lockb?|yarn\.lock|package-lock\.json|pnpm-lock\.yaml|Cargo\.lock|go\.sum|poetry\.lock|uv\.lock)$/,
  /(^|\/)(vitest|jest|playwright|karma|cypress)\.config\.[cm]?[jt]s$/, /(^|\/)(vitest\.workspace|jest\.setup)\.[cm]?[jt]s$/,
  /(^|\/)(pyproject\.toml|pytest\.ini|setup\.cfg|tox\.ini|conftest\.py|Cargo\.toml|go\.mod|Makefile)$/,
  /^\.github\//, /^\.gitlab-ci\.yml$/, /^\.circleci\//,
]

// Editing the harness is how a green run lies (SPEC §6).
const isProtected = path => PROTECTED.some(re => re.test(path))

function paths(dir, runId) {
  const base = String(dir).replace(/\/+$/, '')
  // Worktrees sit beside the repo, not in it: inside, the user's own test runner
  // would collect every test in every forge worktree.
  const wtRoot = `${base}.forge/${runId}`
  return { dir: base, runDir: `${base}/.claude/runs/${runId}`, wtRoot, main: `${wtRoot}/main`, branch: `forge/${runId}/main` }
}

function ledgerLine(kind, text, sha) {
  return `[${kind}] ${text}${sha ? ` @${String(sha).slice(0, 7)}` : ''}`
}

// No pipe: zsh (the Bash tool's shell here) has no PIPESTATUS, so `suite | tail`
// would report tail's exit code and every suite would read as green.
const suiteCommand = (cmd, logFile) => `( ${cmd} ) > ${q(logFile)} 2>&1; e=$?; tail -c 3000 ${q(logFile)}; exit $e`

// A run is green when it fails nothing that was not already failing at baseline.
// On a green baseline the exit code must also be 0: an import error removes a
// whole file from the report without adding a failing case.
function suiteOk(res, baselineFailing = []) {
  const known = new Set(baselineFailing)
  const fresh = res.cases.filter(c => c.outcome === 'fail' && !known.has(`${c.file} › ${c.name}`))
  return fresh.length === 0 && (known.size > 0 || res.exit === 0)
}

// Helpers that spawn agents. They use the workflow runtime's `agent` global, so
// they are tested through the scenario checks, not in isolation.

// ---------- stops ----------

function stop(status, reason) {
  const e = new Error(`forge ${status}: ${reason}`)
  e.forge = { status, reason }
  throw e
}

// Phases return stops as data: an error's own fields may not survive workflow().
async function guard(out, body) {
  try {
    return await body()
  } catch (e) {
    if (e && e.forge) return { ...out, stop: e.forge }
    throw e
  }
}

// ---------- prompt plumbing ----------

// The one machine-readable line every forge prompt carries (harness contract).
const withCtx = (text, ctx) => `${text}\n\nFORGE_CTX ${JSON.stringify(ctx)}`

const str = { type: 'string' }
const obj = (properties, required = Object.keys(properties)) => ({ type: 'object', properties, required })
const arr = items => ({ type: 'array', items })

// ---------- runner ----------

const RUNNER_PROMPT =
  'You are the forge runner. Execute every command in FORGE_CTX.commands with the Bash tool, ' +
  'in order, in its `cwd`, exactly as written. Never fix, retry, reorder, skip or add a command, ' +
  'even after a failure. For each command return its exit code and the last `tail` characters ' +
  '(default 4000) of combined stdout and stderr, verbatim. One result per command, in order.'
const RUNNER_SCHEMA = obj({ results: arr(obj({ cmd: str, exit: { type: 'integer' }, tail: str })) })

async function run(label, commands) {
  const r = await agent(withCtx(RUNNER_PROMPT, { commands }), {
    label: `runner:${label}`, model: 'sonnet', effort: 'low', schema: RUNNER_SCHEMA,
  })
  const results = r && Array.isArray(r.results) ? r.results : []
  if (results.length !== commands.length) stop('error', `runner:${label} returned ${results.length}/${commands.length} results`)
  return results
}

async function runOk(label, commands) {
  const results = await run(label, commands)
  const i = results.findIndex(x => x.exit !== 0)
  if (i >= 0) stop('error', `runner:${label}: \`${commands[i].cmd}\` exited ${results[i].exit}: ${String(results[i].tail).slice(-400)}`)
  return results
}

function shaOf(tail) {
  const m = String(tail).match(/\b[0-9a-f]{40}\b/)
  if (!m) stop('error', `expected a commit sha, got: ${String(tail).slice(0, 80)}`)
  return m[0]
}

async function commit(label, cwd, message, { amend = false } = {}) {
  const cmd = amend ? 'git add -A && git commit -q --allow-empty --amend --no-edit' : `git add -A && git commit -q --allow-empty -m ${q(message)}`
  const [, head] = await runOk(label, [{ cmd, cwd }, { cmd: 'git rev-parse HEAD', cwd }])
  return shaOf(head.tail)
}

// An agent told not to commit may commit anyway; a clean tree would then hide its
// edits from porcelain. HEAD must still be where the script left it.
async function protectedChanges(label, cwd, expectedHead) {
  const [head, status] = await runOk(label, [
    { cmd: 'git rev-parse HEAD', cwd },
    { cmd: 'git status --porcelain=v1 -uall', cwd, tail: 100000 },
  ])
  const now = shaOf(head.tail)
  if (now !== expectedHead) stop('blocked', `${label}: the agent committed on its own (HEAD ${now.slice(0, 7)}, expected ${expectedHead.slice(0, 7)})`)
  const changed = parsePorcelain(status.tail)
  return { changed, touched: changed.filter(isProtected) }
}

// Files changed between two commits, limited to `files` — the tamper check.
async function editedBetween(label, cwd, from, to, files) {
  if (!files.length) return []
  const [r] = await runOk(label, [{ cmd: `git diff --name-only ${from} ${to} -- ${files.map(q).join(' ')}`, cwd, tail: 100000 }])
  return r.tail.split('\n').filter(Boolean)
}

// Runs the suite with a JUnit report. Only the tags are returned — a small surface
// for the runner to transcribe.
async function runTests(label, { cwd, testCmd, runDir }) {
  const out = `${runDir}/junit/${label}.xml`
  const jc = junitCommand(testCmd, out)
  if (!jc) stop('escalated', `no JUnit adapter yet for the test command "${testCmd}"`)
  const [clean, suite, report] = await run(`test:${label}`, [
    { cmd: 'test -z "$(git status --porcelain)"', cwd },
    { cmd: `mkdir -p ${q(`${runDir}/junit`)} && rm -f ${q(out)} && ${suiteCommand(jc, `${runDir}/junit/${label}.log`)}`, cwd, tail: 3000 },
    { cmd: `grep -oE '<testcase [^>]*>|</testcase>|<(failure|error) type="[^"]*"|<skipped' ${q(out)}`, cwd, tail: 400000 },
  ])
  if (clean.exit !== 0) stop('blocked', `tree not clean before the test run in ${cwd}`)
  return { exit: suite.exit, tail: suite.tail, cases: parseJunit(report.tail) }
}

// ---------- scribe ----------

const SCRIBE_PROMPT =
  'You are the forge scribe. For each entry in FORGE_CTX.writes, write `content` to `path` exactly, ' +
  'byte for byte, creating parent directories. Then run `shasum -a 256 <path>` and `wc -c < <path>` ' +
  'and report the hash and byte count from that output — never compute or copy them yourself.'
const SCRIBE_SCHEMA = obj({ files: arr(obj({ path: str, sha256: str, bytes: { type: 'integer' } })) })

const serialize = v => (typeof v === 'string' ? v : `${JSON.stringify(v, null, 2)}\n`)

// The hash is computed here and compared with the scribe's shasum: a scribe that
// skips or mangles a write cannot produce the right one.
async function persist(label, writes) {
  const list = Object.entries(writes).map(([path, v]) => ({ path, content: serialize(v) }))
  if (!list.length) return
  const r = await agent(withCtx(SCRIBE_PROMPT, { writes: list }), {
    label: `scribe:${label}`, model: 'haiku', effort: 'low', schema: SCRIBE_SCHEMA,
  })
  const got = new Map(((r && r.files) || []).map(f => [f.path, f]))
  for (const w of list) {
    const f = got.get(w.path)
    if (!f || f.sha256 !== sha256(w.content)) stop('error', `write-hash-mismatch: ${w.path}`)
  }
  // The scribe could hash the content without writing it. The runner, a separate
  // agent, reads the file back from disk.
  const checks = await run(`verify:${label}`, list.map(w => ({ cmd: `shasum -a 256 ${q(w.path)} && wc -c < ${q(w.path)}`, cwd: '/' })))
  list.forEach((w, i) => {
    const [hash, bytes] = [checks[i].tail.match(/\b[0-9a-f]{64}\b/), checks[i].tail.trim().split(/\s+/).pop()]
    if (checks[i].exit !== 0 || !hash || hash[0] !== sha256(w.content) || Number(bytes) !== byteLength(w.content)) {
      stop('error', `write-hash-mismatch on disk: ${w.path}`)
    }
  })
}

// ---------- judge ----------

const JUDGE_PROMPT =
  'You are the forge judge. Each item in FORGE_CTX.items pairs a spec clause with a test that claims ' +
  'to check it. You see no implementation, on purpose; do not look for one and do not use tools. ' +
  'For each item return one verdict, keyed by the item\'s `ref`:\n' +
  '- valid: the test fails for any implementation that violates the clause and passes for one that meets it.\n' +
  '- too_weak: a wrong implementation could still pass (e.g. the clause expects 401, the test asserts only "not 200").\n' +
  '- overreach: the test demands behavior the clause does not state.\n' +
  '- wrong_oracle: the expected value contradicts the clause.'
const JUDGE_SCHEMA = obj({
  verdicts: arr(obj({ ref: str, verdict: { type: 'string', enum: ['valid', 'too_weak', 'overreach', 'wrong_oracle'] } })),
})

const clauseView = c => ({ id: c.id, kind: c.kind, input: c.input, action: c.action, expected: c.expected })

// Returns one verdict per item, in order; an item the judge skipped is 'missing'.
// Verdicts bind to a ref, not a test name: two items may share a name.
async function judge(label, list) {
  const items = list.map((item, i) => ({ ref: String(i + 1), ...item }))
  const r = await agent(withCtx(JUDGE_PROMPT, { items }), {
    label: `judge:${label}`, model: 'opus', effort: 'medium', schema: JUDGE_SCHEMA,
  })
  const verdicts = (r && r.verdicts) || []
  return items.map(i => {
    const v = verdicts.find(x => x.ref === i.ref)
    return v ? v.verdict : 'missing'
  })
}

// ---------- role schemas ----------

const clauseSchema = obj({ id: str, kind: str, input: str, action: str, expected: str, source: str })
const SCOUT_SCHEMA = obj({
  files: arr(str), helpers: arr(str), conventions: str,
  signals: arr(obj({ id: { type: 'string', enum: ['persistence', 'auth', 'money', 'concurrency', 'untrusted-input', 'public-api', 'data-loss'] }, where: str })),
  commands: obj({ install: { type: ['string', 'null'] }, test: str, fast: str, typecheck: { type: ['string', 'null'] }, lint: { type: ['string', 'null'] } }),
})
const PLAN_SCHEMA = obj({
  slices: arr(obj({
    id: str, title: str, files: arr(str), spec: arr(clauseSchema),
    acceptance: arr(obj({ clause: str, level: { type: 'string', enum: ['unit', 'integration', 'e2e'] } })),
    structure: str, depends_on: arr(str), notes: { type: 'string', maxLength: 600 },
  }, ['id', 'title', 'files', 'spec', 'acceptance', 'structure', 'depends_on', 'notes'])),
  rejected: arr(obj({ id: str, reason: str })),
})
const CRITIC_SCHEMA = obj({ verdicts: arr(obj({ clause: str, verdict: str })) })
const BUILDER_A_SCHEMA = obj({
  tests: arr(obj({ clause: str, file: str, name: str, lines: { type: 'array', items: { type: 'integer' }, minItems: 2, maxItems: 2 } })),
})
const DONE_SCHEMA = obj({ done: { type: 'boolean' } })
const RED_SCHEMA = obj({
  bugs: arr(obj({ id: str, clause: str, variants: { type: 'array', items: obj({ file: str, name: str }), minItems: 2, maxItems: 2 } })),
})
const BLUE_SCHEMA = obj({
  results: arr(obj({ bug: str, outcome: { type: 'string', enum: ['fixed', 'reject'] }, clause: str })),
})
const REVIEW_SCHEMA = obj({
  findings: arr(obj({ file: str, line: { type: 'integer' }, category: str, blocking: { type: 'boolean' }, summary: str })),
})


const PLANNER_PROMPT =
  'You are the forge planner. Plan FORGE_CTX.task for the repository the scout described in FORGE_CTX.scout. ' +
  'Return vertical slices, walking skeleton first; each slice touches data, behavior and test end to end. ' +
  'Each slice carries typed clauses — the contract every later phase binds to. A clause is ' +
  '{id "S<n>.<m>", kind, input, action, expected, source}; `expected` is exact (a status code, a value), never "an error". ' +
  'Kinds: behavior (new, must fail before the change), negative (what must NOT happen), preserve (existing ' +
  'behavior that must survive), migration, concurrency, property. ' +
  'Every slice must hold a clause of the kind each risk signal in FORGE_CTX.signals requires: ' +
  'auth, money, data-loss → negative; persistence → migration or negative; concurrency → concurrency; ' +
  'untrusted-input → property or negative; public-api → preserve. ' +
  'If FORGE_CTX.feedback is set, it lists problems with your previous plan: fix exactly those.'
const CRITIC_PROMPT =
  'You are the forge clause critic. For each clause in FORGE_CTX.clauses return one verdict: ok, ambiguous ' +
  '(two readings lead to different tests), untestable (no executable check can decide it), or ' +
  'contradicts:<id> (conflicts with another clause). Judge each clause as written; do not rewrite it.'

const { task, scout, signals = [], tier } = args
const out = { ledger: [] }
let asked = 0

const ask = feedback => agent(withCtx(PLANNER_PROMPT, { task, scout, signals, feedback }), {
  label: `planner:${++asked}`, model: 'opus', effort: tier === 'S' ? 'medium' : 'xhigh', schema: PLAN_SCHEMA,
})

async function critique(plan) {
  const clauses = plan.slices.flatMap(s => s.spec.map(clauseView))
  const r = await agent(withCtx(CRITIC_PROMPT, { clauses }), { label: 'critic', model: 'sonnet', effort: 'medium', schema: CRITIC_SCHEMA })
  const verdicts = (r && r.verdicts) || []
  return clauses
    .map(c => ({ clause: c.id, verdict: (verdicts.find(v => v.clause === c.id) || { verdict: 'missing' }).verdict }))
    .filter(v => v.verdict !== 'ok')
}

return await guard(out, async () => {
  let plan = await ask(null)
  let problems = checkPlan(plan, { signals })
  if (problems.length) {
    out.ledger.push(ledgerLine('failed', `plan check: ${problems.join('; ')}`))
    plan = await ask({ problems })
    problems = checkPlan(plan, { signals })
  }
  out.plan = plan
  if (problems.length) stop('escalated', `plan check failed twice: ${problems.join('; ')}`)

  let flagged = await critique(plan)
  if (flagged.length) {
    out.ledger.push(ledgerLine('failed', `clause check: ${flagged.map(f => `${f.clause} ${f.verdict}`).join(', ')}`))
    plan = await ask({ critic: flagged })
    problems = checkPlan(plan, { signals })
    out.plan = plan
    if (problems.length) stop('escalated', `plan check failed after the critic round: ${problems.join('; ')}`)
    flagged = await critique(plan)
  }
  // No checkpoint shows these at low risk, so a clause still flagged stops the run.
  if (flagged.length) stop('escalated', `clauses still flagged: ${flagged.map(f => `${f.clause} ${f.verdict}`).join(', ')}`)
  const count = plan.slices.reduce((n, s) => n + s.spec.length, 0)
  out.ledger.push(ledgerLine('verified', `plan: ${plan.slices.length} slice(s), ${count} clause(s) pass the plan and clause checks`))
  return out
})
