export const meta = {
  name: 'forge-duel',
  description: 'forge phase: red attacks at commit A, judge on variant 1, blue fixes, recheck with the held-out variant 2',
}
// GENERATED by forge/build.js from forge/src — edit there, then run `bun build.js`.
// Pure helpers shared by every forge phase. No imports, no I/O: build.js strips
// `export` and inlines this file into each workflow script.

// ---------- sha256 (scripts have no crypto API) ----------

const SHA_K = [
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]

function utf8Bytes(str) {
  const out = []
  for (const ch of str) {
    const c = ch.codePointAt(0)
    if (c < 0x80) out.push(c)
    else if (c < 0x800) out.push(0xc0 | (c >> 6), 0x80 | (c & 63))
    else if (c < 0x10000) out.push(0xe0 | (c >> 12), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63))
    else out.push(0xf0 | (c >> 18), 0x80 | ((c >> 12) & 63), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63))
  }
  return out
}

const rotr = (x, n) => (x >>> n) | (x << (32 - n))

function sha256(str) {
  const bytes = utf8Bytes(str)
  const bitLen = bytes.length * 8
  bytes.push(0x80)
  while (bytes.length % 64 !== 56) bytes.push(0)
  const hi = Math.floor(bitLen / 0x100000000)
  const lo = bitLen >>> 0
  bytes.push((hi >>> 24) & 255, (hi >>> 16) & 255, (hi >>> 8) & 255, hi & 255,
    (lo >>> 24) & 255, (lo >>> 16) & 255, (lo >>> 8) & 255, lo & 255)
  const H = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]
  const W = new Array(64)
  for (let i = 0; i < bytes.length; i += 64) {
    for (let t = 0; t < 16; t++) {
      W[t] = (bytes[i + 4 * t] << 24) | (bytes[i + 4 * t + 1] << 16) | (bytes[i + 4 * t + 2] << 8) | bytes[i + 4 * t + 3]
    }
    for (let t = 16; t < 64; t++) {
      const s0 = rotr(W[t - 15], 7) ^ rotr(W[t - 15], 18) ^ (W[t - 15] >>> 3)
      const s1 = rotr(W[t - 2], 17) ^ rotr(W[t - 2], 19) ^ (W[t - 2] >>> 10)
      W[t] = (W[t - 16] + s0 + W[t - 7] + s1) | 0
    }
    let [a, b, c, d, e, f, g, h] = H
    for (let t = 0; t < 64; t++) {
      const t1 = (h + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ (~e & g)) + SHA_K[t] + W[t]) | 0
      const t2 = ((rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) | 0
      h = g; g = f; f = e; e = (d + t1) | 0; d = c; c = b; b = a; a = (t1 + t2) | 0
    }
    H[0] = (H[0] + a) | 0; H[1] = (H[1] + b) | 0; H[2] = (H[2] + c) | 0; H[3] = (H[3] + d) | 0
    H[4] = (H[4] + e) | 0; H[5] = (H[5] + f) | 0; H[6] = (H[6] + g) | 0; H[7] = (H[7] + h) | 0
  }
  return H.map(x => (x >>> 0).toString(16).padStart(8, '0')).join('')
}

// ---------- JUnit ----------

function unescapeXml(s) {
  return s
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&')
}

const normFile = f => (f || '').replace(/^\.\//, '')

// Reads full JUnit XML or the grep stream the runner returns (open tags, closing
// tags and `<failure type="…"` fragments, one per line).
function parseJunit(xml) {
  const cases = []
  for (const m of String(xml).matchAll(/<testcase\b([^>]*?)(\/>|>([\s\S]*?)<\/testcase>)/g)) {
    const attrs = {}
    for (const a of m[1].matchAll(/([\w:-]+)="([^"]*)"/g)) attrs[a[1]] = unescapeXml(a[2])
    const body = m[3] || ''
    const failure = body.match(/<(?:failure|error)\b[^>]*?\btype="([^"]*)"/)
    const failed = /<(?:failure|error)\b/.test(body)
    cases.push({
      name: attrs.name,
      file: normFile(attrs.file),
      outcome: failed ? 'fail' : /<skipped\b/.test(body) ? 'skip' : 'pass',
      failureType: failed ? (failure ? unescapeXml(failure[1]) : '') : null,
    })
  }
  return cases
}

// A test missing from the report was never collected: an import or compile error
// removes the whole file from bun's XML.
function outcomes(tests, cases) {
  return tests.map(t => {
    const c = cases.find(k => k.name === t.name && k.file === normFile(t.file))
    return c ? c.outcome : 'not-collected'
  })
}

function junitCommand(testCmd, outFile) {
  if (/^bun test\b/.test(testCmd)) return `${testCmd} --reporter=junit --reporter-outfile=${q(outFile)}`
  return null
}

// ---------- triage ----------

const SIGNALS = ['persistence', 'auth', 'money', 'concurrency', 'untrusted-input', 'public-api', 'data-loss']
const TIERS = ['S', 'M', 'L']

function sizeOf(files, newModules = 0) {
  const n = new Set(files).size
  if (n > 8) return 'L'
  if (n > 2 || newModules > 0) return 'M'
  return 'S'
}

const raiseTier = (a, b) => (TIERS.indexOf(a) >= TIERS.indexOf(b) ? a : b)

function riskOf(signals, dismissedIds) {
  const live = signals.filter(s => !dismissedIds.includes(s.id))
  return { risk: live.length ? 'high' : 'low', signals: live }
}

function parseDismiss(list) {
  return (list || []).map(item => {
    const m = String(item).match(/^\s*([\w-]+)\s*:\s*(\S.*)$/)
    if (!m) throw new Error(`dismiss "${item}" needs a reason: "<signal id>: <reason>"`)
    return { id: m[1], reason: m[2].trim() }
  })
}

// SPEC §6 table — the only source for council, shadow, checkpoints and attackers.
function dosing(tier, risk) {
  const high = risk === 'high'
  const small = tier === 'S'
  return {
    council: !small && high,
    shadow: high,
    checkpointAfterPlan: !(small && !high),
    checkpointAfterSlice: !small && high,
    attackers: high ? ['opus', 'opus'] : [small ? 'sonnet' : 'opus'],
    mutation: high,
  }
}

// ---------- plan checks ----------

const KINDS = ['behavior', 'negative', 'preserve', 'migration', 'concurrency', 'property']
const REQUIRED = {
  auth: ['negative'],
  persistence: ['migration', 'negative'],
  concurrency: ['concurrency'],
  'untrusted-input': ['property', 'negative'],
  money: ['negative'],
  'data-loss': ['negative'],
  'public-api': ['preserve'],
}
const CLAUSE_FIELDS = ['id', 'kind', 'input', 'action', 'expected', 'source']

function checkPlan(plan, { signals = [], sources = [] } = {}) {
  const slices = (plan && plan.slices) || []
  if (!slices.length) return ['plan has no slices']
  const problems = []
  const seen = new Set()
  const used = new Set()
  const signalIds = [...new Set(signals.map(s => s.id))]
  for (const slice of slices) {
    if (!slice.files || !slice.files.length) problems.push(`${slice.id}: no files`)
    if (!slice.spec || !slice.spec.length) { problems.push(`${slice.id}: no clauses`); continue }
    for (const c of slice.spec) {
      for (const f of CLAUSE_FIELDS) if (typeof c[f] !== 'string' || !c[f].trim()) problems.push(`${c.id || slice.id}: empty ${f}`)
      if (c.kind && !KINDS.includes(c.kind)) problems.push(`${c.id}: unknown kind ${c.kind}`)
      if (seen.has(c.id)) problems.push(`duplicate clause id ${c.id}`)
      seen.add(c.id)
      used.add(c.source)
    }
    for (const id of signalIds) {
      const need = REQUIRED[id]
      if (need && !slice.spec.some(c => need.includes(c.kind))) {
        problems.push(`${slice.id}: signal ${id} needs a ${need.join(' or ')} clause`)
      }
    }
  }
  const rejected = new Set(((plan && plan.rejected) || []).map(r => r.id))
  for (const s of sources) if (!used.has(s) && !rejected.has(s)) problems.push(`${s} is neither a clause source nor rejected`)
  return problems
}

// ---------- git, shell, run layout ----------

const q = s => `'${String(s).replace(/'/g, `'\\''`)}'`

const unquotePath = p => (p.startsWith('"') && p.endsWith('"') ? JSON.parse(p) : p)

function parsePorcelain(text) {
  return String(text).split('\n').filter(l => l.length > 3).map(l => {
    const path = l.slice(3)
    const arrow = path.indexOf(' -> ')
    return unquotePath(arrow >= 0 ? path.slice(arrow + 4) : path)
  })
}

const PROTECTED = [
  /(^|\/)package\.json$/, /(^|\/)bunfig\.toml$/, /(^|\/)tsconfig[^/]*\.json$/,
  /(^|\/)(bun\.lockb?|yarn\.lock|package-lock\.json|pnpm-lock\.yaml|Cargo\.lock|go\.sum|poetry\.lock|uv\.lock)$/,
  /(^|\/)(vitest|jest|playwright|karma|cypress)\.config\.[cm]?[jt]s$/, /(^|\/)(vitest\.workspace|jest\.setup)\.[cm]?[jt]s$/,
  /(^|\/)(pyproject\.toml|pytest\.ini|setup\.cfg|tox\.ini|conftest\.py|Cargo\.toml|go\.mod|Makefile)$/,
  /^\.github\//, /^\.gitlab-ci\.yml$/, /^\.circleci\//,
]

// Editing the harness is how a green run lies (SPEC §6).
const isProtected = path => PROTECTED.some(re => re.test(path))

function paths(dir, runId) {
  const base = String(dir).replace(/\/+$/, '')
  // Worktrees sit beside the repo, not in it: inside, the user's own test runner
  // would collect every test in every forge worktree.
  const wtRoot = `${base}.forge/${runId}`
  return { dir: base, runDir: `${base}/.claude/runs/${runId}`, wtRoot, main: `${wtRoot}/main`, branch: `forge/${runId}/main` }
}

function ledgerLine(kind, text, sha) {
  return `[${kind}] ${text}${sha ? ` @${String(sha).slice(0, 7)}` : ''}`
}

// Helpers that spawn agents. They use the workflow runtime's `agent` global, so
// they are tested through the scenario checks, not in isolation.

// ---------- stops ----------

function stop(status, reason) {
  const e = new Error(`forge ${status}: ${reason}`)
  e.forge = { status, reason }
  throw e
}

// Phases return stops as data: an error's own fields may not survive workflow().
async function guard(out, body) {
  try {
    return await body()
  } catch (e) {
    if (e && e.forge) return { ...out, stop: e.forge }
    throw e
  }
}

// ---------- prompt plumbing ----------

// The one machine-readable line every forge prompt carries (harness contract).
const withCtx = (text, ctx) => `${text}\n\nFORGE_CTX ${JSON.stringify(ctx)}`

const str = { type: 'string' }
const obj = (properties, required = Object.keys(properties)) => ({ type: 'object', properties, required })
const arr = items => ({ type: 'array', items })

// ---------- runner ----------

const RUNNER_PROMPT =
  'You are the forge runner. Execute every command in FORGE_CTX.commands with the Bash tool, ' +
  'in order, in its `cwd`, exactly as written. Never fix, retry, reorder, skip or add a command, ' +
  'even after a failure. For each command return its exit code and the last `tail` characters ' +
  '(default 4000) of combined stdout and stderr, verbatim. One result per command, in order.'
const RUNNER_SCHEMA = obj({ results: arr(obj({ cmd: str, exit: { type: 'integer' }, tail: str })) })

async function run(label, commands) {
  const r = await agent(withCtx(RUNNER_PROMPT, { commands }), {
    label: `runner:${label}`, model: 'sonnet', effort: 'low', schema: RUNNER_SCHEMA,
  })
  const results = r && Array.isArray(r.results) ? r.results : []
  if (results.length !== commands.length) stop('error', `runner:${label} returned ${results.length}/${commands.length} results`)
  return results
}

async function runOk(label, commands) {
  const results = await run(label, commands)
  const i = results.findIndex(x => x.exit !== 0)
  if (i >= 0) stop('error', `runner:${label}: \`${commands[i].cmd}\` exited ${results[i].exit}: ${String(results[i].tail).slice(-400)}`)
  return results
}

function shaOf(tail) {
  const m = String(tail).match(/\b[0-9a-f]{40}\b/)
  if (!m) stop('error', `expected a commit sha, got: ${String(tail).slice(0, 80)}`)
  return m[0]
}

async function commit(label, cwd, message, { amend = false } = {}) {
  const cmd = amend ? 'git add -A && git commit -q --allow-empty --amend --no-edit' : `git add -A && git commit -q --allow-empty -m ${q(message)}`
  const [, head] = await runOk(label, [{ cmd, cwd }, { cmd: 'git rev-parse HEAD', cwd }])
  return shaOf(head.tail)
}

async function changedFiles(label, cwd) {
  const [r] = await runOk(label, [{ cmd: 'git status --porcelain=v1 -uall', cwd, tail: 100000 }])
  return parsePorcelain(r.tail)
}

async function protectedChanges(label, cwd) {
  const changed = await changedFiles(label, cwd)
  return { changed, touched: changed.filter(isProtected) }
}

// Runs the suite with a JUnit report. Only the tags are returned — a small surface
// for the runner to transcribe.
async function runTests(label, { cwd, testCmd, runDir }) {
  const out = `${runDir}/junit/${label}.xml`
  const jc = junitCommand(testCmd, out)
  if (!jc) stop('escalated', `no JUnit adapter yet for the test command "${testCmd}"`)
  const [clean, suite, report] = await run(`test:${label}`, [
    { cmd: 'test -z "$(git status --porcelain)"', cwd },
    { cmd: `mkdir -p ${q(`${runDir}/junit`)} && rm -f ${q(out)} && ${jc} 2>&1 | tail -c 3000; exit \${PIPESTATUS[0]}`, cwd, tail: 3000 },
    { cmd: `grep -oE '<testcase [^>]*>|</testcase>|<(failure|error) type="[^"]*"|<skipped' ${q(out)}`, cwd, tail: 400000 },
  ])
  if (clean.exit !== 0) stop('blocked', `tree not clean before the test run in ${cwd}`)
  return { exit: suite.exit, tail: suite.tail, cases: parseJunit(report.tail) }
}

// ---------- scribe ----------

const SCRIBE_PROMPT =
  'You are the forge scribe. For each entry in FORGE_CTX.writes, write `content` to `path` exactly, ' +
  'byte for byte, creating parent directories. Then run `shasum -a 256 <path>` and `wc -c < <path>` ' +
  'and report the hash and byte count from that output — never compute or copy them yourself.'
const SCRIBE_SCHEMA = obj({ files: arr(obj({ path: str, sha256: str, bytes: { type: 'integer' } })) })

const serialize = v => (typeof v === 'string' ? v : `${JSON.stringify(v, null, 2)}\n`)

// The hash is computed here and compared with the scribe's shasum: a scribe that
// skips or mangles a write cannot produce the right one.
async function persist(label, writes) {
  const list = Object.entries(writes).map(([path, v]) => ({ path, content: serialize(v) }))
  if (!list.length) return
  const r = await agent(withCtx(SCRIBE_PROMPT, { writes: list }), {
    label: `scribe:${label}`, model: 'haiku', effort: 'low', schema: SCRIBE_SCHEMA,
  })
  const got = new Map(((r && r.files) || []).map(f => [f.path, f]))
  for (const w of list) {
    const f = got.get(w.path)
    if (!f || f.sha256 !== sha256(w.content)) stop('error', `write-hash-mismatch: ${w.path}`)
  }
}

// ---------- judge ----------

const JUDGE_PROMPT =
  'You are the forge judge. Each item in FORGE_CTX.items pairs a spec clause with a test that claims ' +
  'to check it. You see no implementation, on purpose; do not look for one and do not use tools. ' +
  'For each item return one verdict:\n' +
  '- valid: the test fails for any implementation that violates the clause and passes for one that meets it.\n' +
  '- too_weak: a wrong implementation could still pass (e.g. the clause expects 401, the test asserts only "not 200").\n' +
  '- overreach: the test demands behavior the clause does not state.\n' +
  '- wrong_oracle: the expected value contradicts the clause.'
const JUDGE_SCHEMA = obj({
  verdicts: arr(obj({ test: str, verdict: { type: 'string', enum: ['valid', 'too_weak', 'overreach', 'wrong_oracle'] } })),
})

const clauseView = c => ({ id: c.id, kind: c.kind, input: c.input, action: c.action, expected: c.expected })

// Returns one verdict per item, in order; an item the judge skipped is 'missing'.
async function judge(label, items) {
  const r = await agent(withCtx(JUDGE_PROMPT, { items }), {
    label: `judge:${label}`, model: 'opus', effort: 'medium', schema: JUDGE_SCHEMA,
  })
  const verdicts = (r && r.verdicts) || []
  return items.map(i => {
    const v = verdicts.find(x => x.test === i.test)
    return v ? v.verdict : 'missing'
  })
}

// ---------- role schemas ----------

const clauseSchema = obj({ id: str, kind: str, input: str, action: str, expected: str, source: str })
const SCOUT_SCHEMA = obj({
  files: arr(str), helpers: arr(str), conventions: str,
  signals: arr(obj({ id: { type: 'string', enum: ['persistence', 'auth', 'money', 'concurrency', 'untrusted-input', 'public-api', 'data-loss'] }, where: str })),
  commands: obj({ test: str, fast: str, typecheck: { type: ['string', 'null'] }, lint: { type: ['string', 'null'] } }),
})
const PLAN_SCHEMA = obj({
  slices: arr(obj({
    id: str, title: str, files: arr(str), spec: arr(clauseSchema),
    acceptance: arr(obj({ clause: str, level: { type: 'string', enum: ['unit', 'integration', 'e2e'] } })),
    structure: str, depends_on: arr(str), notes: { type: 'string', maxLength: 600 },
  }, ['id', 'title', 'files', 'spec', 'acceptance', 'structure', 'depends_on', 'notes'])),
  rejected: arr(obj({ id: str, reason: str })),
})
const CRITIC_SCHEMA = obj({ verdicts: arr(obj({ clause: str, verdict: str })) })
const BUILDER_A_SCHEMA = obj({
  tests: arr(obj({ clause: str, file: str, name: str, lines: { type: 'array', items: { type: 'integer' }, minItems: 2, maxItems: 2 } })),
})
const DONE_SCHEMA = obj({ done: { type: 'boolean' } })
const RED_SCHEMA = obj({
  bugs: arr(obj({ id: str, clause: str, variants: { type: 'array', items: obj({ file: str, name: str }), minItems: 2, maxItems: 2 } })),
})
const BLUE_SCHEMA = obj({
  results: arr(obj({ bug: str, outcome: { type: 'string', enum: ['fixed', 'reject'] }, clause: str })),
})
const REVIEW_SCHEMA = obj({
  findings: arr(obj({ file: str, line: { type: 'integer' }, category: str, blocking: { type: 'boolean' }, summary: str })),
})


const RED_PROMPT =
  'You are a forge red attacker. FORGE_CTX.worktree is checked out at the commit holding the tests and stubs ' +
  'for FORGE_CTX.slice — the implementation is deliberately absent. Find up to 5 ways an implementation could ' +
  'meet every existing test yet violate a clause of the slice spec. For each bug write TWO independent test ' +
  'variants, each in a NEW test file (never edit an existing file), each asserting the clause on different ' +
  'inputs. Cite the clause id. Do not commit. Return each bug with its clause and its two {file, name} variants.'
const BLUE_PROMPT =
  'You are the forge blue fixer. Each bug in FORGE_CTX.bugs comes with a failing test that a judge confirmed ' +
  'against its clause. In FORGE_CTX.worktree, fix the root cause in the implementation so the clause holds for ' +
  'every input, not just the one tested. Never edit a test file. Do not commit. If a bug is not a real ' +
  'violation of its clause, return outcome "reject" for it instead of changing code.'

const { slice, record: rec, paths: P, runId, testCmd, attackers, mutation, round = 1 } = args
const out = { ledger: [], slice: rec }
rec.duel = rec.duel || { rounds: [] }
const R = { round, bugs: [] }
rec.duel.rounds.push(R)
const clauseIds = new Set(slice.spec.map(c => c.id))
const clauses = Object.fromEntries(slice.spec.map(c => [c.id, c]))
const temp = []
const tag = a => `${slice.id}-r${round}-a${a}`
const key = b => `a${b.attacker}/${b.id}`

async function worktreeAt(label, path, sha) {
  temp.push(path)
  await runOk(label, [{ cmd: `git worktree add -q --detach ${q(path)} ${sha}`, cwd: P.main }])
}

// A scratch tree at `sha` with the given red files checked out and committed, so
// the clean-tree rule holds for the test run.
async function scratchRun(label, sha, picks) {
  const path = `${P.wtRoot}/scratch-${label}`
  await worktreeAt(`scratch:${label}`, path, sha)
  const cmds = picks.map(p => ({ cmd: `git checkout ${p.sha} -- ${p.files.map(q).join(' ')}`, cwd: path }))
  cmds.push({ cmd: `git add -A && git commit -q --allow-empty -m ${q(`scratch ${label}`)}`, cwd: path })
  await runOk(`scratch:${label}:checkout`, cmds)
  return runTests(label, { cwd: path, testCmd, runDir: P.runDir })
}

const byAttacker = bugs => {
  const m = new Map()
  for (const b of bugs) m.set(b.sha, [...(m.get(b.sha) || []), b])
  return m
}

const record = (b, fields) => {
  const row = { id: b.id, attacker: b.attacker, clause: b.clause, verdict: b.verdict || null, status: null, ...fields }
  R.bugs.push(row)
  return row
}

async function attack() {
  await runOk(`red:worktrees:${slice.id}-r${round}`, attackers.map((_, i) => {
    const path = `${P.wtRoot}/red-${tag(i + 1)}`
    temp.push(path)
    return { cmd: `git worktree add -q --detach ${q(path)} ${rec.commits.A}`, cwd: P.main }
  }))
  const results = await Promise.all(attackers.map((model, i) => agent(
    withCtx(RED_PROMPT, { worktree: `${P.wtRoot}/red-${tag(i + 1)}`, slice, round, attacker: i + 1 }),
    { label: `red:${slice.id}:r${round}:a${i + 1}`, model, effort: 'high', schema: RED_SCHEMA },
  )))
  const found = []
  for (const [i, res] of results.entries()) {
    const bugs = ((res && res.bugs) || []).slice(0, 5)
    if (!bugs.length) continue
    const wt = `${P.wtRoot}/red-${tag(i + 1)}`
    const [, , names, head] = await runOk(`red:commit:${tag(i + 1)}`, [
      { cmd: `git checkout -q -b ${q(`forge/${runId}/red-${tag(i + 1)}`)}`, cwd: wt },
      { cmd: `git add -A && git commit -q --allow-empty -m ${q(`red ${tag(i + 1)}`)}`, cwd: wt },
      { cmd: 'git diff --name-status HEAD~1 HEAD', cwd: wt, tail: 100000 },
      { cmd: 'git rev-parse HEAD', cwd: wt },
    ])
    const status = new Map(names.tail.split('\n').filter(Boolean).map(l => { const [s, ...f] = l.split('\t'); return [f.join('\t'), s] }))
    const sha = shaOf(head.tail)
    for (const b of bugs) {
      const files = (b.variants || []).map(v => v.file)
      // Red may only add files; moving them onto B or main is then conflict-free.
      const ok = clauseIds.has(b.clause) && files.length === 2 && files[0] !== files[1] && files.every(f => status.get(f) === 'A')
      if (!ok) { record({ ...b, attacker: i + 1 }, { status: 'dropped', note: 'must cite a slice clause and add two new files' }); continue }
      found.push({ ...b, attacker: i + 1, sha, v1: b.variants[0], v2: b.variants[1] })
    }
  }
  return found
}

return await guard(out, async () => {
  try {
    const found = await attack()
    if (!found.length) {
      out.ledger.push(ledgerLine('verified', `${slice.id} round ${round}: no bug from ${attackers.length} attacker(s)`, rec.commits.B))
      if (mutation) out.ledger.push(ledgerLine('decision', `${slice.id} mutation: skipped (not implemented in M1)`))
      return out
    }

    // Keep pairs whose two variants both fail correctly against B.
    const atB = await scratchRun(`${slice.id}-r${round}-B`, rec.commits.B, [...byAttacker(found)].map(([sha, bs]) => ({ sha, files: bs.flatMap(b => [b.v1.file, b.v2.file]) })))
    const failing = found.filter(b => outcomes([b.v1, b.v2], atB.cases).every(o => o === 'fail'))
    for (const b of found) if (!failing.includes(b)) record(b, { status: 'dropped', note: 'variants must both fail at B' })
    if (!failing.length) return out

    const [...sources] = await runOk(`red:sources:${slice.id}-r${round}`, failing.map(b => ({ cmd: `git show ${b.sha}:${q(b.v1.file)}`, cwd: P.main, tail: 20000 })))
    const verdicts = await judge(`${slice.id}:r${round}`, failing.map((b, i) => ({ clause: clauseView(clauses[b.clause]), test: b.v1.name, source: sources[i].tail })))
    const valid = []
    failing.forEach((b, i) => {
      b.verdict = verdicts[i]
      if (b.verdict === 'valid') valid.push(b)
      else if (b.verdict === 'overreach') {
        record(b, { status: 'overreach' })
        out.ledger.push(ledgerLine('gap', `${slice.id} ${b.clause}: red test overreaches the clause — a spec gap for the human`))
      } else record(b, { status: 'discarded' })
    })
    if (!valid.length) return out

    // Only variant 1 lands before the fix; variant 2 stays hidden from blue.
    const v1Files = valid.map(b => b.v1.file)
    await runOk(`red:land:${slice.id}-r${round}`, [...byAttacker(valid)].map(([sha, bs]) => ({ cmd: `git checkout ${sha} -- ${bs.map(b => q(b.v1.file)).join(' ')}`, cwd: P.main })))
    rec.commits.R = await commit(`commit:${slice.id}:R${round}`, P.main, `${slice.id} red r${round}`)

    const blue = await agent(withCtx(BLUE_PROMPT, { worktree: P.main, bugs: valid.map(b => ({ id: key(b), clause: b.clause, file: b.v1.file, name: b.v1.name })) }), {
      label: `blue:${slice.id}:r${round}`, agentType: 'implementer', model: 'opus', effort: 'high', schema: BLUE_SCHEMA,
    })
    const outcome = b => ((blue && blue.results) || []).find(r => r.bug === key(b))
    const { touched } = await protectedChanges(`changes:${slice.id}:F${round}`, P.main)
    if (touched.length) {
      rec.protectedTouched = touched
      stop('blocked', `${slice.id} blue touched protected file(s): ${touched.join(', ')}`)
    }
    rec.commits.F = await commit(`commit:${slice.id}:F${round}`, P.main, `${slice.id} fix r${round}`)

    const [diff] = await runOk(`tamper:${slice.id}-r${round}`, [{ cmd: `git diff --name-only ${rec.commits.R} ${rec.commits.F} -- ${v1Files.map(q).join(' ')}`, cwd: P.main, tail: 100000 }])
    const tampered = diff.tail.split('\n').filter(Boolean)
    if (tampered.length) {
      for (const b of valid) record(b, { status: tampered.includes(b.v1.file) ? 'tamper' : 'unchecked' })
      stop('blocked', `${slice.id} tamper: blue edited red test file(s) ${tampered.join(', ')}`)
    }

    const atF = await scratchRun(`${slice.id}-r${round}-F`, rec.commits.F, [...byAttacker(valid)].map(([sha, bs]) => ({ sha, files: bs.map(b => b.v2.file) })))
    const fixed = []
    for (const b of valid) {
      const [o1, o2] = outcomes([b.v1, b.v2], atF.cases)
      const o = outcome(b)
      const status = o && o.outcome === 'reject' ? 'rejected' : o1 !== 'pass' ? 'unfixed' : o2 !== 'pass' ? 'held-out-failed' : 'fixed'
      record(b, { status })
      if (status === 'fixed') fixed.push(b)
    }
    const clauseRows = (rec.atB || []).filter(r => r.file)
    const regressions = outcomes(clauseRows.map(r => ({ file: r.file, name: r.test })), atF.cases).filter(o => o !== 'pass').length
    if (fixed.length) {
      await runOk(`red:heldout:${slice.id}-r${round}`, [...byAttacker(fixed)].map(([sha, bs]) => ({ cmd: `git checkout ${sha} -- ${bs.map(b => q(b.v2.file)).join(' ')}`, cwd: P.main })))
      out.head = await commit(`commit:${slice.id}:H${round}`, P.main, `${slice.id} red held-out r${round}`)
    } else out.head = rec.commits.F
    const open = R.bugs.filter(b => ['rejected', 'unfixed', 'held-out-failed'].includes(b.status))
    if (open.length || regressions || atF.exit !== 0) {
      stop('escalated', `${slice.id} round ${round}: ${open.map(b => `${b.id} ${b.status}`).join(', ') || 'no open bug'}; ${regressions} clause test(s) regressed; suite → ${atF.exit}`)
    }
    out.ledger.push(ledgerLine('verified', `${slice.id} round ${round}: ${fixed.length} bug(s) fixed, variant 2 held out and passing, suite → 0`, out.head))
    return out
  } finally {
    // Red and scratch trees are evidence only while the phase runs; branches stay.
    if (temp.length) await run(`cleanup:${slice.id}-r${round}`, [...temp.map(t => ({ cmd: `git worktree remove --force ${q(t)}`, cwd: P.main })), { cmd: 'git worktree prune', cwd: P.main }])
  }
})
