export const meta = {
  name: 'forge-build',
  description: 'forge phase: one test per clause at commit A, judged blind, then the implementation at commit B',
}
// GENERATED by forge/build.js from forge/src — edit there, then run `bun build.js`.
// Pure helpers shared by every forge phase. No imports, no I/O: build.js strips
// `export` and inlines this file into each workflow script.

// ---------- sha256 (scripts have no crypto API) ----------

const SHA_K = [
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]

function utf8Bytes(str) {
  const out = []
  for (const ch of str) {
    const c = ch.codePointAt(0)
    if (c < 0x80) out.push(c)
    else if (c < 0x800) out.push(0xc0 | (c >> 6), 0x80 | (c & 63))
    else if (c < 0x10000) out.push(0xe0 | (c >> 12), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63))
    else out.push(0xf0 | (c >> 18), 0x80 | ((c >> 12) & 63), 0x80 | ((c >> 6) & 63), 0x80 | (c & 63))
  }
  return out
}

const rotr = (x, n) => (x >>> n) | (x << (32 - n))

function sha256(str) {
  const bytes = utf8Bytes(str)
  const bitLen = bytes.length * 8
  bytes.push(0x80)
  while (bytes.length % 64 !== 56) bytes.push(0)
  const hi = Math.floor(bitLen / 0x100000000)
  const lo = bitLen >>> 0
  bytes.push((hi >>> 24) & 255, (hi >>> 16) & 255, (hi >>> 8) & 255, hi & 255,
    (lo >>> 24) & 255, (lo >>> 16) & 255, (lo >>> 8) & 255, lo & 255)
  const H = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]
  const W = new Array(64)
  for (let i = 0; i < bytes.length; i += 64) {
    for (let t = 0; t < 16; t++) {
      W[t] = (bytes[i + 4 * t] << 24) | (bytes[i + 4 * t + 1] << 16) | (bytes[i + 4 * t + 2] << 8) | bytes[i + 4 * t + 3]
    }
    for (let t = 16; t < 64; t++) {
      const s0 = rotr(W[t - 15], 7) ^ rotr(W[t - 15], 18) ^ (W[t - 15] >>> 3)
      const s1 = rotr(W[t - 2], 17) ^ rotr(W[t - 2], 19) ^ (W[t - 2] >>> 10)
      W[t] = (W[t - 16] + s0 + W[t - 7] + s1) | 0
    }
    let [a, b, c, d, e, f, g, h] = H
    for (let t = 0; t < 64; t++) {
      const t1 = (h + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ (~e & g)) + SHA_K[t] + W[t]) | 0
      const t2 = ((rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) | 0
      h = g; g = f; f = e; e = (d + t1) | 0; d = c; c = b; b = a; a = (t1 + t2) | 0
    }
    H[0] = (H[0] + a) | 0; H[1] = (H[1] + b) | 0; H[2] = (H[2] + c) | 0; H[3] = (H[3] + d) | 0
    H[4] = (H[4] + e) | 0; H[5] = (H[5] + f) | 0; H[6] = (H[6] + g) | 0; H[7] = (H[7] + h) | 0
  }
  return H.map(x => (x >>> 0).toString(16).padStart(8, '0')).join('')
}

// ---------- JUnit ----------

function unescapeXml(s) {
  return s
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&')
}

const normFile = f => (f || '').replace(/^\.\//, '')

// Reads full JUnit XML or the grep stream the runner returns (open tags, closing
// tags and `<failure type="…"` fragments, one per line).
function parseJunit(xml) {
  const cases = []
  for (const m of String(xml).matchAll(/<testcase\b([^>]*?)(\/>|>([\s\S]*?)<\/testcase>)/g)) {
    const attrs = {}
    for (const a of m[1].matchAll(/([\w:-]+)="([^"]*)"/g)) attrs[a[1]] = unescapeXml(a[2])
    const body = m[3] || ''
    const failure = body.match(/<(?:failure|error)\b[^>]*?\btype="([^"]*)"/)
    const failed = /<(?:failure|error)\b/.test(body)
    cases.push({
      name: attrs.name,
      file: normFile(attrs.file),
      outcome: failed ? 'fail' : /<skipped\b/.test(body) ? 'skip' : 'pass',
      failureType: failed ? (failure ? unescapeXml(failure[1]) : '') : null,
    })
  }
  return cases
}

// A test missing from the report was never collected: an import or compile error
// removes the whole file from bun's XML.
function outcomes(tests, cases) {
  return tests.map(t => {
    const c = cases.find(k => k.name === t.name && k.file === normFile(t.file))
    return c ? c.outcome : 'not-collected'
  })
}

function junitCommand(testCmd, outFile) {
  if (/^bun test\b/.test(testCmd)) return `${testCmd} --reporter=junit --reporter-outfile=${q(outFile)}`
  return null
}

// ---------- triage ----------

const SIGNALS = ['persistence', 'auth', 'money', 'concurrency', 'untrusted-input', 'public-api', 'data-loss']
const TIERS = ['S', 'M', 'L']

function sizeOf(files, newModules = 0) {
  const n = new Set(files).size
  if (n > 8) return 'L'
  if (n > 2 || newModules > 0) return 'M'
  return 'S'
}

const raiseTier = (a, b) => (TIERS.indexOf(a) >= TIERS.indexOf(b) ? a : b)

function riskOf(signals, dismissedIds) {
  const live = signals.filter(s => !dismissedIds.includes(s.id))
  return { risk: live.length ? 'high' : 'low', signals: live }
}

function parseDismiss(list) {
  return (list || []).map(item => {
    const m = String(item).match(/^\s*([\w-]+)\s*:\s*(\S.*)$/)
    if (!m) throw new Error(`dismiss "${item}" needs a reason: "<signal id>: <reason>"`)
    return { id: m[1], reason: m[2].trim() }
  })
}

// SPEC §6 table — the only source for council, shadow, checkpoints and attackers.
function dosing(tier, risk) {
  const high = risk === 'high'
  const small = tier === 'S'
  return {
    council: !small && high,
    shadow: high,
    checkpointAfterPlan: !(small && !high),
    checkpointAfterSlice: !small && high,
    attackers: high ? ['opus', 'opus'] : [small ? 'sonnet' : 'opus'],
    mutation: high,
  }
}

// ---------- plan checks ----------

const KINDS = ['behavior', 'negative', 'preserve', 'migration', 'concurrency', 'property']
const REQUIRED = {
  auth: ['negative'],
  persistence: ['migration', 'negative'],
  concurrency: ['concurrency'],
  'untrusted-input': ['property', 'negative'],
  money: ['negative'],
  'data-loss': ['negative'],
  'public-api': ['preserve'],
}
const CLAUSE_FIELDS = ['id', 'kind', 'input', 'action', 'expected', 'source']

function checkPlan(plan, { signals = [], sources = [] } = {}) {
  const slices = (plan && plan.slices) || []
  if (!slices.length) return ['plan has no slices']
  const problems = []
  const seen = new Set()
  const used = new Set()
  const signalIds = [...new Set(signals.map(s => s.id))]
  for (const slice of slices) {
    if (!slice.files || !slice.files.length) problems.push(`${slice.id}: no files`)
    if (!slice.spec || !slice.spec.length) { problems.push(`${slice.id}: no clauses`); continue }
    for (const c of slice.spec) {
      for (const f of CLAUSE_FIELDS) if (typeof c[f] !== 'string' || !c[f].trim()) problems.push(`${c.id || slice.id}: empty ${f}`)
      if (c.kind && !KINDS.includes(c.kind)) problems.push(`${c.id}: unknown kind ${c.kind}`)
      if (seen.has(c.id)) problems.push(`duplicate clause id ${c.id}`)
      seen.add(c.id)
      used.add(c.source)
    }
    for (const id of signalIds) {
      const need = REQUIRED[id]
      if (need && !slice.spec.some(c => need.includes(c.kind))) {
        problems.push(`${slice.id}: signal ${id} needs a ${need.join(' or ')} clause`)
      }
    }
  }
  const rejected = new Set(((plan && plan.rejected) || []).map(r => r.id))
  for (const s of sources) if (!used.has(s) && !rejected.has(s)) problems.push(`${s} is neither a clause source nor rejected`)
  return problems
}

// ---------- git, shell, run layout ----------

const q = s => `'${String(s).replace(/'/g, `'\\''`)}'`

const unquotePath = p => (p.startsWith('"') && p.endsWith('"') ? JSON.parse(p) : p)

function parsePorcelain(text) {
  return String(text).split('\n').filter(l => l.length > 3).map(l => {
    const path = l.slice(3)
    const arrow = path.indexOf(' -> ')
    return unquotePath(arrow >= 0 ? path.slice(arrow + 4) : path)
  })
}

const PROTECTED = [
  /(^|\/)package\.json$/, /(^|\/)bunfig\.toml$/, /(^|\/)tsconfig[^/]*\.json$/,
  /(^|\/)(bun\.lockb?|yarn\.lock|package-lock\.json|pnpm-lock\.yaml|Cargo\.lock|go\.sum|poetry\.lock|uv\.lock)$/,
  /(^|\/)(vitest|jest|playwright|karma|cypress)\.config\.[cm]?[jt]s$/, /(^|\/)(vitest\.workspace|jest\.setup)\.[cm]?[jt]s$/,
  /(^|\/)(pyproject\.toml|pytest\.ini|setup\.cfg|tox\.ini|conftest\.py|Cargo\.toml|go\.mod|Makefile)$/,
  /^\.github\//, /^\.gitlab-ci\.yml$/, /^\.circleci\//,
]

// Editing the harness is how a green run lies (SPEC §6).
const isProtected = path => PROTECTED.some(re => re.test(path))

function paths(dir, runId) {
  const base = String(dir).replace(/\/+$/, '')
  // Worktrees sit beside the repo, not in it: inside, the user's own test runner
  // would collect every test in every forge worktree.
  const wtRoot = `${base}.forge/${runId}`
  return { dir: base, runDir: `${base}/.claude/runs/${runId}`, wtRoot, main: `${wtRoot}/main`, branch: `forge/${runId}/main` }
}

function ledgerLine(kind, text, sha) {
  return `[${kind}] ${text}${sha ? ` @${String(sha).slice(0, 7)}` : ''}`
}

// Helpers that spawn agents. They use the workflow runtime's `agent` global, so
// they are tested through the scenario checks, not in isolation.

// ---------- stops ----------

function stop(status, reason) {
  const e = new Error(`forge ${status}: ${reason}`)
  e.forge = { status, reason }
  throw e
}

// Phases return stops as data: an error's own fields may not survive workflow().
async function guard(out, body) {
  try {
    return await body()
  } catch (e) {
    if (e && e.forge) return { ...out, stop: e.forge }
    throw e
  }
}

// ---------- prompt plumbing ----------

// The one machine-readable line every forge prompt carries (harness contract).
const withCtx = (text, ctx) => `${text}\n\nFORGE_CTX ${JSON.stringify(ctx)}`

const str = { type: 'string' }
const obj = (properties, required = Object.keys(properties)) => ({ type: 'object', properties, required })
const arr = items => ({ type: 'array', items })

// ---------- runner ----------

const RUNNER_PROMPT =
  'You are the forge runner. Execute every command in FORGE_CTX.commands with the Bash tool, ' +
  'in order, in its `cwd`, exactly as written. Never fix, retry, reorder, skip or add a command, ' +
  'even after a failure. For each command return its exit code and the last `tail` characters ' +
  '(default 4000) of combined stdout and stderr, verbatim. One result per command, in order.'
const RUNNER_SCHEMA = obj({ results: arr(obj({ cmd: str, exit: { type: 'integer' }, tail: str })) })

async function run(label, commands) {
  const r = await agent(withCtx(RUNNER_PROMPT, { commands }), {
    label: `runner:${label}`, model: 'sonnet', effort: 'low', schema: RUNNER_SCHEMA,
  })
  const results = r && Array.isArray(r.results) ? r.results : []
  if (results.length !== commands.length) stop('error', `runner:${label} returned ${results.length}/${commands.length} results`)
  return results
}

async function runOk(label, commands) {
  const results = await run(label, commands)
  const i = results.findIndex(x => x.exit !== 0)
  if (i >= 0) stop('error', `runner:${label}: \`${commands[i].cmd}\` exited ${results[i].exit}: ${String(results[i].tail).slice(-400)}`)
  return results
}

function shaOf(tail) {
  const m = String(tail).match(/\b[0-9a-f]{40}\b/)
  if (!m) stop('error', `expected a commit sha, got: ${String(tail).slice(0, 80)}`)
  return m[0]
}

async function commit(label, cwd, message, { amend = false } = {}) {
  const cmd = amend ? 'git add -A && git commit -q --allow-empty --amend --no-edit' : `git add -A && git commit -q --allow-empty -m ${q(message)}`
  const [, head] = await runOk(label, [{ cmd, cwd }, { cmd: 'git rev-parse HEAD', cwd }])
  return shaOf(head.tail)
}

async function changedFiles(label, cwd) {
  const [r] = await runOk(label, [{ cmd: 'git status --porcelain=v1 -uall', cwd, tail: 100000 }])
  return parsePorcelain(r.tail)
}

async function protectedChanges(label, cwd) {
  const changed = await changedFiles(label, cwd)
  return { changed, touched: changed.filter(isProtected) }
}

// Runs the suite with a JUnit report. Only the tags are returned — a small surface
// for the runner to transcribe.
async function runTests(label, { cwd, testCmd, runDir }) {
  const out = `${runDir}/junit/${label}.xml`
  const jc = junitCommand(testCmd, out)
  if (!jc) stop('escalated', `no JUnit adapter yet for the test command "${testCmd}"`)
  const [clean, suite, report] = await run(`test:${label}`, [
    { cmd: 'test -z "$(git status --porcelain)"', cwd },
    { cmd: `mkdir -p ${q(`${runDir}/junit`)} && rm -f ${q(out)} && ${jc} 2>&1 | tail -c 3000; exit \${PIPESTATUS[0]}`, cwd, tail: 3000 },
    { cmd: `grep -oE '<testcase [^>]*>|</testcase>|<(failure|error) type="[^"]*"|<skipped' ${q(out)}`, cwd, tail: 400000 },
  ])
  if (clean.exit !== 0) stop('blocked', `tree not clean before the test run in ${cwd}`)
  return { exit: suite.exit, tail: suite.tail, cases: parseJunit(report.tail) }
}

// ---------- scribe ----------

const SCRIBE_PROMPT =
  'You are the forge scribe. For each entry in FORGE_CTX.writes, write `content` to `path` exactly, ' +
  'byte for byte, creating parent directories. Then run `shasum -a 256 <path>` and `wc -c < <path>` ' +
  'and report the hash and byte count from that output — never compute or copy them yourself.'
const SCRIBE_SCHEMA = obj({ files: arr(obj({ path: str, sha256: str, bytes: { type: 'integer' } })) })

const serialize = v => (typeof v === 'string' ? v : `${JSON.stringify(v, null, 2)}\n`)

// The hash is computed here and compared with the scribe's shasum: a scribe that
// skips or mangles a write cannot produce the right one.
async function persist(label, writes) {
  const list = Object.entries(writes).map(([path, v]) => ({ path, content: serialize(v) }))
  if (!list.length) return
  const r = await agent(withCtx(SCRIBE_PROMPT, { writes: list }), {
    label: `scribe:${label}`, model: 'haiku', effort: 'low', schema: SCRIBE_SCHEMA,
  })
  const got = new Map(((r && r.files) || []).map(f => [f.path, f]))
  for (const w of list) {
    const f = got.get(w.path)
    if (!f || f.sha256 !== sha256(w.content)) stop('error', `write-hash-mismatch: ${w.path}`)
  }
}

// ---------- judge ----------

const JUDGE_PROMPT =
  'You are the forge judge. Each item in FORGE_CTX.items pairs a spec clause with a test that claims ' +
  'to check it. You see no implementation, on purpose; do not look for one and do not use tools. ' +
  'For each item return one verdict:\n' +
  '- valid: the test fails for any implementation that violates the clause and passes for one that meets it.\n' +
  '- too_weak: a wrong implementation could still pass (e.g. the clause expects 401, the test asserts only "not 200").\n' +
  '- overreach: the test demands behavior the clause does not state.\n' +
  '- wrong_oracle: the expected value contradicts the clause.'
const JUDGE_SCHEMA = obj({
  verdicts: arr(obj({ test: str, verdict: { type: 'string', enum: ['valid', 'too_weak', 'overreach', 'wrong_oracle'] } })),
})

const clauseView = c => ({ id: c.id, kind: c.kind, input: c.input, action: c.action, expected: c.expected })

// Returns one verdict per item, in order; an item the judge skipped is 'missing'.
async function judge(label, items) {
  const r = await agent(withCtx(JUDGE_PROMPT, { items }), {
    label: `judge:${label}`, model: 'opus', effort: 'medium', schema: JUDGE_SCHEMA,
  })
  const verdicts = (r && r.verdicts) || []
  return items.map(i => {
    const v = verdicts.find(x => x.test === i.test)
    return v ? v.verdict : 'missing'
  })
}

// ---------- role schemas ----------

const clauseSchema = obj({ id: str, kind: str, input: str, action: str, expected: str, source: str })
const SCOUT_SCHEMA = obj({
  files: arr(str), helpers: arr(str), conventions: str,
  signals: arr(obj({ id: { type: 'string', enum: ['persistence', 'auth', 'money', 'concurrency', 'untrusted-input', 'public-api', 'data-loss'] }, where: str })),
  commands: obj({ test: str, fast: str, typecheck: { type: ['string', 'null'] }, lint: { type: ['string', 'null'] } }),
})
const PLAN_SCHEMA = obj({
  slices: arr(obj({
    id: str, title: str, files: arr(str), spec: arr(clauseSchema),
    acceptance: arr(obj({ clause: str, level: { type: 'string', enum: ['unit', 'integration', 'e2e'] } })),
    structure: str, depends_on: arr(str), notes: { type: 'string', maxLength: 600 },
  }, ['id', 'title', 'files', 'spec', 'acceptance', 'structure', 'depends_on', 'notes'])),
  rejected: arr(obj({ id: str, reason: str })),
})
const CRITIC_SCHEMA = obj({ verdicts: arr(obj({ clause: str, verdict: str })) })
const BUILDER_A_SCHEMA = obj({
  tests: arr(obj({ clause: str, file: str, name: str, lines: { type: 'array', items: { type: 'integer' }, minItems: 2, maxItems: 2 } })),
})
const DONE_SCHEMA = obj({ done: { type: 'boolean' } })
const RED_SCHEMA = obj({
  bugs: arr(obj({ id: str, clause: str, variants: { type: 'array', items: obj({ file: str, name: str }), minItems: 2, maxItems: 2 } })),
})
const BLUE_SCHEMA = obj({
  results: arr(obj({ bug: str, outcome: { type: 'string', enum: ['fixed', 'reject'] }, clause: str })),
})
const REVIEW_SCHEMA = obj({
  findings: arr(obj({ file: str, line: { type: 'integer' }, category: str, blocking: { type: 'boolean' }, summary: str })),
})


const BUILDER_A_PROMPT =
  'Stage A of a forge slice. In FORGE_CTX.worktree, write one test per clause of FORGE_CTX.slice.spec, ' +
  'plus stubs so the tests compile and run: signatures only, bodies that throw "not implemented". ' +
  'No implementation. Each test name starts with its clause id. behavior, negative, migration, concurrency ' +
  'and property tests must fail against the stubs; preserve tests must pass today. Do not commit, and do ' +
  'not touch test config, package scripts, lockfiles or CI. Return, per clause, the test file, the test ' +
  'name, and the [first, last] line numbers of the whole test block. If FORGE_CTX.retry is set, the judge ' +
  'rejected those tests: strengthen exactly those.'
const BUILDER_B_PROMPT =
  'Stage B of a forge slice. In FORGE_CTX.worktree, implement FORGE_CTX.slice so every test in ' +
  'FORGE_CTX.tests passes, with the smallest change that does it. Do not edit those tests, do not commit, ' +
  'and do not touch test config, package scripts, lockfiles or CI. If FORGE_CTX.failures is set, your ' +
  'previous attempt left those tests failing; the tail is the suite output.'

const { slice, paths: P, testCmd } = args
const rec = { id: slice.id, status: 'running', commits: {}, judge: [], atA: [], atB: [], protectedTouched: [], outOfScope: [] }
const out = { ledger: [], slice: rec }
const clauses = Object.fromEntries(slice.spec.map(c => [c.id, c]))
const mustFailAtA = kind => kind !== 'preserve'

async function checkChanges(label) {
  const { changed, touched } = await protectedChanges(label, P.main)
  if (touched.length) {
    rec.protectedTouched = touched
    stop('blocked', `${slice.id} touched protected file(s): ${touched.join(', ')}`)
  }
  for (const f of changed) if (!slice.files.includes(f) && !rec.outOfScope.includes(f)) rec.outOfScope.push(f)
}

const row = (t, outcome) => ({ test: t.name, file: t.file, clause: t.clause, kind: clauses[t.clause].kind, outcome })

return await guard(out, async () => {
  let tests = []
  let retry = null
  for (let attempt = 1; ; attempt++) {
    const res = await agent(withCtx(BUILDER_A_PROMPT, { stage: 'A', worktree: P.main, slice, retry }), {
      label: `builder:${slice.id}:A${attempt}`, agentType: 'implementer', model: 'opus', effort: 'high', schema: BUILDER_A_SCHEMA,
    })
    tests = ((res && res.tests) || []).filter(t => clauses[t.clause])
    await checkChanges(`changes:${slice.id}:A${attempt}`)
    const missing = slice.spec.filter(c => !tests.some(t => t.clause === c.id)).map(c => ({ clause: c.id, verdict: 'missing' }))
    let bad = missing
    if (!missing.length) {
      // The judge sees the test block only, extracted by the runner — never the stub.
      const sources = await runOk(`sources:${slice.id}:A${attempt}`, tests.map(t => ({
        cmd: `sed -n ${Number(t.lines[0])},${Number(t.lines[1])}p ${q(t.file)}`, cwd: P.main, tail: 20000,
      })))
      const items = tests.map((t, i) => ({ clause: clauseView(clauses[t.clause]), test: t.name, source: sources[i].tail }))
      const verdicts = await judge(`${slice.id}:A${attempt}`, items)
      tests.forEach((t, i) => rec.judge.push({ test: t.name, clause: t.clause, verdict: verdicts[i], attempt }))
      for (const [i, v] of verdicts.entries()) if (v === 'overreach') out.ledger.push(ledgerLine('gap', `${slice.id} ${tests[i].clause}: builder test overreaches the clause`))
      bad = tests.map((t, i) => ({ clause: t.clause, test: t.name, verdict: verdicts[i] }))
        .filter(x => x.verdict === 'too_weak' || x.verdict === 'wrong_oracle' || x.verdict === 'missing')
    }
    if (!bad.length) break
    if (attempt === 2) stop('escalated', `${slice.id} builder tests rejected twice: ${bad.map(b => `${b.clause} ${b.verdict}`).join(', ')}`)
    retry = bad
  }

  rec.commits.A = await commit(`commit:${slice.id}:A`, P.main, `${slice.id} tests`)
  const atA = await runTests(`${slice.id}-A`, { cwd: P.main, testCmd, runDir: P.runDir })
  rec.atA = tests.map((t, i) => row(t, outcomes(tests, atA.cases)[i]))
  const wrongAtA = rec.atA.filter(r => (mustFailAtA(r.kind) ? r.outcome !== 'fail' : r.outcome !== 'pass'))
  if (wrongAtA.length) {
    stop('failed', `${slice.id} at A: ${wrongAtA.map(r => `${r.clause} ${r.outcome} (${r.kind} must ${mustFailAtA(r.kind) ? 'fail' : 'pass'})`).join(', ')}`)
  }
  out.ledger.push(ledgerLine('verified', `${slice.id} at A: ${rec.atA.length} clause test(s) fail or pass as their kind requires`, rec.commits.A))

  let failures = null
  for (let attempt = 1; ; attempt++) {
    await agent(withCtx(BUILDER_B_PROMPT, { stage: 'B', worktree: P.main, slice, tests, failures }), {
      label: `builder:${slice.id}:B${attempt}`, agentType: 'implementer', model: 'opus', effort: 'high', schema: DONE_SCHEMA,
    })
    await checkChanges(`changes:${slice.id}:B${attempt}`)
    // Attempt 2 amends B on the run's private branch, so B~1 stays A.
    rec.commits.B = await commit(`commit:${slice.id}:B${attempt}`, P.main, `${slice.id} impl`, { amend: attempt > 1 })
    const atB = await runTests(`${slice.id}-B${attempt}`, { cwd: P.main, testCmd, runDir: P.runDir })
    rec.atB = tests.map((t, i) => row(t, outcomes(tests, atB.cases)[i]))
    const failing = rec.atB.filter(r => r.outcome !== 'pass')
    if (!failing.length && atB.exit === 0) {
      out.ledger.push(ledgerLine('verified', `${testCmd} → 0`, rec.commits.B))
      break
    }
    out.ledger.push(ledgerLine('failed', `${slice.id} attempt ${attempt} at B: ${testCmd} → ${atB.exit}, ${failing.length} clause test(s) not passing`, rec.commits.B))
    if (attempt === 2) stop('failed', `${slice.id} still failing at B after 2 attempts`)
    failures = { tests: failing.map(r => r.test), tail: atB.tail }
  }
  rec.status = 'built'
  return out
})
