// Workflow scripts cannot import, so each phase ships with lib + runtime inlined.
// `bun build.js` writes ../<name>.js; `bun build.js --check` fails on a stale file.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const SRC = join(import.meta.dir, 'src')
export const OUT = join(import.meta.dir, '..')
export const PHASES = ['forge', 'forge-triage', 'forge-plan', 'forge-build', 'forge-duel', 'forge-close']
const MARK = '\n// @lib\n'

const shared = () => ['lib.js', 'runtime.js']
  .map(f => readFileSync(join(SRC, f), 'utf8').replace(/^import [^\n]*\n/gm, '').replace(/^export /gm, ''))
  .join('\n')

export function render(name) {
  const src = readFileSync(join(SRC, 'phases', `${name}.js`), 'utf8')
  if (!src.startsWith('export const meta') || !src.includes(MARK)) {
    throw new Error(`src/phases/${name}.js must start with its meta literal and contain a "// @lib" line`)
  }
  const banner = `\n// GENERATED by forge/build.js from forge/src — edit there, then run \`bun build.js\`.\n`
  return src.replace(MARK, `${banner}${shared()}\n`)
}

export function stale() {
  return PHASES.filter(name => {
    const out = join(OUT, `${name}.js`)
    return !existsSync(out) || readFileSync(out, 'utf8') !== render(name)
  })
}

if (import.meta.main) {
  if (process.argv.includes('--check')) {
    const s = stale()
    if (s.length) { console.error(`stale: ${s.join(', ')} — run \`bun build.js\``); process.exit(1) }
  } else {
    for (const name of PHASES) writeFileSync(join(OUT, `${name}.js`), render(name))
  }
}
